language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
install:
  - pip install . --use-mirrors
  - pip install nose mock coverage pep8 --use-mirrors
script:
  - nosetests --with-coverage --cover-package gantry
  - pep8
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
